### PR TITLE
Fixes the example codes in AttributeOverrides javadoc

### PR DESCRIPTION
**Pull request by hantsy**
Add missing `name` attribute to the example codes in AttributeOverrides javadoc.

### CODE REVIEW

**Review by dmatej — APPROVED** [review]

**Comment by dmatej** [comment]
Interesting, it was correct in AttributeOverride, but the name was missing in AttributeOverrides annotation.

**Comment by lukasj** [comment]
would the one merging this mind to fix the build? See https://www.eclipse.org/lists/jpa-dev/msg00160.html for details. Thanks

**Comment by hantsy** [comment]
@lukasj It seems to need to update the copyright year.

**Comment by lukasj** [comment]
right. I'd expect either the author of this PR or the person who merged this to fix it (read as "provides the PR fixing this").

**Comment by dmatej** [comment]
> right. I'd expect either the author of this PR or the person who merged this to fix it (read as "provides the PR fixing this").

I hear you, that always happens when I believe it is a sure simple thing so I don't need to run the build locally :-D
Or better build system should verify pull requests ...

**Comment by hantsy** [comment]
@dmatej Why not consider Github actions to build the project, thus it will forbid PR to merge if there are build error in the build workflow.

**Comment by dmatej** [comment]
> @dmatej Why not consider Github actions to build the project, thus it will forbid PR to merge if there are build error in the build workflow.

It seems that it is already configured, but as you were not a committer of the project, the build did not start automatically and nothing warned me before the merge that I should have initiated the build.
For my pr it started automatically.
Next time we will do that better 🙂

**Comment by lukasj** [comment]
the problem is in a way the gh action - the checkout part there in particular - does work. The GF copyright plugin sees *all* files as modified in a year at which the checkout has been done, even those unchanged by the recent commit. To avoid this false alarms, there is `-Dcopyright.ignoreyear=true` option in the GH action build for now. Unfortunately I haven't found a way to get around this problem (yet?).

**Pull request merged**
