### PR TITLE
Make the name member of @XxxxGenerator annotations optional

### PR DESCRIPTION
**Pull request by gavinking**
See #406.

### CODE REVIEW

**Review by lukasj — APPROVED** [review]

**Review by lukasj — COMMENTED** [review]
the deafult name should be defined as: _SEQUENCE_ENTITYNAME_ for the class level use annotation and _SEQUENCE_ENTITYNAME_FIELDNAME_ for the field level use of the annotation

**Comment by lukasj** [comment]
add a line to appendixes.adoc/changelog

**Comment by gavinking** [comment]
>  the deafult name should be defined as: SEQUENCE_ENTITYNAME for the class level use annotation and SEQUENCE_ENTITYNAME_FIELDNAME for the field level use of the annotation

@lukasj after reviewing this and re-thinking it through properly this time, I realized that what we talked about isn't quite right, and I actually got it right the first time.

We need the `generator` name inferred for `@GeneratedValue` to line up with the name inferred for a `@SequenceGenerator` or `@TableGenerator`. Since the `@GeneratedValue` doesn't know what kind of generator it's looking for, nor where it's declared, the plain entity name is the right thing to use here.

If we want to nail down the actual inferred name of the database sequence or table when `sequenceName` or `table` is missing, that's something we could do, but it's an orthogonal question, since the spec currently doesn't currently constrain that at all. (It just says _"Defaults to a name chosen by persistence provider"_.)

So I think we should merge this as-is.

Sorry for the confusion.

**Comment by gavinking** [comment]
> add a line to appendixes.adoc/changelog

Done.

**Review by lukasj — APPROVED** [review]

**Pull request merged**
