### PR TITLE
introduce @Column(secondPrecision) & clarify semantics of @Column members

### PR DESCRIPTION
**Pull request by gavinking**
see #563

### CODE REVIEW

**Review by lukasj — COMMENTED** [review]
the new _secondPrecision_ member needs to be added also to __orm_3.2.xsd__

**Comment by gavinking** [comment]
> the new _secondPrecision_ member needs to be added also to **orm_3.2.xsd**

Pushed. Did I do it right?

**Comment by lukasj** [comment]
> > the new _secondPrecision_ member needs to be added also to **orm_3.2.xsd**
> 
> Pushed. Did I do it right?

Almost, but you're getting there. _MapKeyColumn_ is there too

**Comment by gavinking** [comment]
I didn't add anything new to `MapKeyColumn`, just synchronized the javadoc.

And I don't think `secondPrecision()` would make sense for `MapKeyColumn`.

**Comment by lukasj** [comment]
> I didn't add anything new to `MapKeyColumn`, just synchronized the javadoc.

Ah, right, an oversight on my end, sorry.

**Review by lukasj — APPROVED** [review]

**Pull request merged**
