### PR TITLE
Typesafe operations for controlling find() queries

### PR DESCRIPTION
**Pull request by gavinking**
See #383.

- Added the `Find` interface.
- Also added a way to set the cache modes for a `Query`, and the `EntityGraph` for a `TypedQuery`.

### CODE REVIEW

**Comment by trajano** [comment]
`with...` as long as it is fluent

**Comment by gavinking** [comment]
@trajano The argument against that is that we should keep names consistent across `Query` and `Finder`. So I'm uncertain which way to go on this.

**Comment by trajano** [comment]
I would prefer we mark the non-fluent `set` methods as deprecated and replace with `with` if it is fluent.  Convention-wise `with` we expect it to `return this` whereas `set` we don't.

**Comment by gavinking** [comment]
@trajano after discussing with @lukasj last night, we have decided to go in a completely different direction.

**Comment by trajano** [comment]
Can you link to the different direction @gavinking

**Comment by gavinking** [comment]
https://github.com/jakartaee/persistence/issues/383#issuecomment-1673920733

https://github.com/jakartaee/persistence/pull/454

**Pull request closed without merging**
