### PR TITLE
make identification variables (and the SELECT) clause optional in JPQL

### PR DESCRIPTION
**Pull request by gavinking**
This is a minimal change to support the subset in Jakarta Data i.e. it is only allowed when there is just one thing in the `FROM` clause.

see #452

### CODE REVIEW

**Comment by gavinking** [comment]
Interesting. I came up with an alternative approach that in certain ways is even more "minimal".

We could say that whenever the identification variable is missing (in a range declaration, or in a path expression) then it is implicitly assigned the variable `this`. 

So you could write:

```sql
select this from Entity where name like :name
```

And that would be equivalent to:

```sql
select this from Entity this where this.name like :name
```

I actually like this quite a lot. WDYT @lukasj?

**Comment by gavinking** [comment]
> We could say that whenever the identification variable is missing (in a range declaration, or in a path expression) then it is implicitly assigned the variable this.

I pushed a second commit which shows what that would look like.

**Review by lukasj — APPROVED** [review]

**Comment by lukasj** [comment]
it looks better with `this`, thanks!

**Comment by gavinking** [comment]
Awesome! 🎉🎉🎉

**Pull request merged**
